#!/bin/sh

PATH="/home/inaba/appstack-5.6.25-0/frameworks/laravel/app/Console:/home/inaba/appstack-5.6.25-0/frameworks/cakephp/bin:/home/inaba/appstack-5.6.25-0/frameworks/codeigniter/bin:/home/inaba/appstack-5.6.25-0/frameworks/symfony/bin:/home/inaba/appstack-5.6.25-0/frameworks/zendframework/app/Console:/home/inaba/appstack-5.6.25-0/git/bin:/home/inaba/appstack-5.6.25-0/varnish/bin:/home/inaba/appstack-5.6.25-0/sqlite/bin:/home/inaba/appstack-5.6.25-0/php/bin:/home/inaba/appstack-5.6.25-0/postgresql/bin:/home/inaba/appstack-5.6.25-0/apache2/bin:/home/inaba/appstack-5.6.25-0/common/bin:$PATH"
BITNAMI_ROOT="/home/inaba/appstack-5.6.25-0"
export BITNAMI_ROOT

exec bash --rcfile "/home/inaba/appstack-5.6.25-0/.bitnamirc"
                    