#!/bin/sh

. /home/inaba/appstack-5.6.25-0/scripts/setenv.sh
SASL_PATH="/home/inaba/appstack-5.6.25-0/common/lib/sasl2"
                export SASL_PATH
exec /home/inaba/appstack-5.6.25-0/common/sbin/.testsaslauthd.bin -f "/home/inaba/appstack-5.6.25-0/common/etc/sasldb2" "$@"
